version: 2.1

description: |
  Simplify running danger in a Github repo

orbs:
  ruby: sue445/ruby-orbs@1.4.0

jobs:
  danger-ruby:
    description: |
      Run danger-ruby in the current project.

      $DANGER_GITHUB_API_TOKEN is required.
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Danger
          command: |
            if [ -n "$DANGER_GITHUB_API_TOKEN" ]; then
              bundle exec danger --fail-on-errors=true
            else
              echo "Not running danger because $DANGER_GITHUB_API_TOKEN is not found"
            fi
