version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.3.0

jobs:
  validate:
    docker:
      - image: circleci/circleci-cli:0.1.2709
    steps:
      - checkout
      - run: "echo -e \"token: placeholder\nverbose: false > ~/.circleci/cli.yml\""
      - run: bash scripts/validate-orbs.sh

workflows:
  orbs:
    jobs:
      - validate:
          name: "Validate Orbs"

      - orb-tools/publish:
          name: "iOS: Publish Dev"
          orb-path: src/ios/orb.yml
          orb-ref: "wordpress-mobile/ios@dev:${CIRCLE_BRANCH}"
          requires: ["Validate Orbs"]
      
      - orb-tools/publish:
          name: "Android: Publish Dev"
          orb-path: src/android/orb.yml
          orb-ref: "wordpress-mobile/android@dev:${CIRCLE_BRANCH}"
          requires: ["Validate Orbs"]

      - orb-tools/publish:
          name: "Danger: Publish Dev"
          orb-path: src/danger/orb.yml
          orb-ref: "wordpress-mobile/danger@dev:${CIRCLE_BRANCH}"
          requires: ["Validate Orbs"]

      - orb-tools/publish:
          name: "iOS: Publish"
          orb-path: src/ios/orb.yml
          orb-ref: "wordpress-mobile/ios@${CIRCLE_TAG}"
          requires: ["Validate Orbs"]
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

      - orb-tools/publish:
          name: "Android: Publish"
          orb-path: src/android/orb.yml
          orb-ref: "wordpress-mobile/android@${CIRCLE_TAG}"
          requires: ["Validate Orbs"]
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

      - orb-tools/publish:
          name: "Danger: Publish"
          orb-path: src/danger/orb.yml
          orb-ref: "wordpress-mobile/danger@${CIRCLE_TAG}"
          requires: ["Validate Orbs"]
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
