version: 2.1

description: |
  Simplify common tasks for building and testing iOS projects

dependency_parameters: &dependency_parameters
  cache-prefix:
    description: A prefix to use for the dependencies cache key.
    type: string
    default: ios-{{ .Environment.CIRCLE_JOB }}
  bundle-install:
    description: Should 'bundle install' be run? If true, 'bundle exec' will be used for CocoaPods commands.
    type: boolean
    default: true
  bundler-working-directory:
    description: The directory containing your project's Gemfile.
    type: string
    default: .
  pod-install:
    description: Should 'pod install' be run?
    type: boolean
    default: true
  cocoapods-working-directory:
    description: The directory containing your project's Podfile and Podfile.lock.
    type: string
    default: .
  carthage-update:
    description: Should 'carthage update' be run?
    type: boolean
    default: false
  carthage-working-directory:
    description: The directory containing your project's Cartfile.
    type: string
    default: .

executor_parameter: &executor_parameter
  xcode-version:
    description: The Xcode version to use.
    type: string
    default: "10.1.0"

executors:
  default:
    description: |
      An executor with sensible defaults for iOS builds.
      See supported versions here: https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
    parameters:
      xcode-version:
        description: The Xcode version to use.
        type: string
        default: "10.1.0"
    macos:
      xcode: << parameters.xcode-version >>

jobs:
  test:
    description: |
      Build and test an iOS project using xcodebuild
    parameters:
      # Executor options
      <<: *executor_parameter
      # Build options
      workspace:
        description: Workspace parameter to be passed to xcodebuild. e.g. MyProject.xcworkspace. A workspace or a project is required.
        type: string
        default: ""
      project:
        description: Project parameter to be passed to xcodebuild. e.g. MyProject.xcodeproj. A workspace or a project is required.
        type: string
        default: ""
      scheme:
        description: Scheme parameter for xcodebuild. e.g. MyProject. A scheme or a target is required.
        type: string
        default: ""
      target:
        description: Target parameter for xcodebuild. e.g. MyProject. A scheme or a target is required.
        type: string
        default: ""
      configuration:
        description: Configuration paramter for xcodebuild. e.g. Debug.
        type: string
        default: Debug
      ios-version:
        description: The iOS simulator version to run tests on.
        type: string
        default: "12.1"
      device:
        description: The iOS simulator device to run tests on.
        type: string
        default: iPhone XS
      # Dependency options
      <<: *dependency_parameters
    executor:
      name: default
      xcode-version: << parameters.xcode-version >>
    steps:
      - run:
          # xcodebuild can behave unpredictably if the simulator is not already booted, so we boot it explicitly here
          name: Boot simulator
          command: |
            # Get the UDID of the "<< parameters.device >>" with "iOS << parameters.ios-version >>"
            DEVICES_KEY="iOS << parameters.ios-version >>"

            # Xcode 10.2 changes the format of `xcrun simctl list -j`
            # The 'devices' object now uses the runtime identifiers as its keys instead of the iOS version
            if [ $(ruby -e "puts '<< parameters.xcode-version >>' >= '10.2.0'") == "true" ]; then
              DEVICES_KEY=$(xcrun simctl list -j | jq -r '[.runtimes[] | select (.name == "iOS << parameters.ios-version >>")][0] | .identifier')
            fi

            UDID=$(xcrun simctl list -j | jq -r "[.devices[\"$DEVICES_KEY\"][] | select(.name | test(\"<< parameters.device >>\"; \"i\")) | select (.availability == \"(available)\")][0] | .udid")

            xcrun simctl boot $UDID # Boot simulator in the background
            echo "export SIMULATOR_UDID=$UDID" >> $BASH_ENV
          background: true
      - checkout
      - install-dependencies:
          cache-prefix: << parameters.cache-prefix >>
          bundle-install: << parameters.bundle-install >>
          bundler-working-directory: << parameters.bundler-working-directory >>
          pod-install: << parameters.pod-install >>
          cocoapods-working-directory: << parameters.cocoapods-working-directory >>
          carthage-update: << parameters.carthage-update >>
          carthage-working-directory: << parameters.carthage-working-directory >>
      - run:
          name: Prepare xcodebuild parameters
          command: |
            optional_argument () {
              OPTION="$1"
              VALUE="$2"
              if [[ ! -z "$VALUE" ]]; then
                echo -n "${OPTION} '${VALUE}'"
              fi
            }

            XCODEBUILD_ARGS="COMPILER_INDEX_STORE_ENABLE=NO"
            XCODEBUILD_ARGS="${XCODEBUILD_ARGS} $(optional_argument "-workspace" "<< parameters.workspace >>")"
            XCODEBUILD_ARGS="${XCODEBUILD_ARGS} $(optional_argument "-project" "<< parameters.project >>")"
            XCODEBUILD_ARGS="${XCODEBUILD_ARGS} $(optional_argument "-scheme" "<< parameters.scheme >>")"
            XCODEBUILD_ARGS="${XCODEBUILD_ARGS} $(optional_argument "-target" "<< parameters.target >>")"
            XCODEBUILD_ARGS="${XCODEBUILD_ARGS} -configuration '<< parameters.configuration >>'"
            XCODEBUILD_ARGS="${XCODEBUILD_ARGS} -sdk iphonesimulator"

            echo "export XCODEBUILD_ARGS='${XCODEBUILD_ARGS}'" >> $BASH_ENV

            echo "Finished building xcodebuild parameters:"
            echo "${XCODEBUILD_ARGS}"
      - run:
          name: Build
          command: |
            mkdir ~/logs
            xcodebuild build-for-testing $XCODEBUILD_ARGS | tee ~/logs/build.log | xcpretty
      - run:
          name: Wait for simulator
          command: |
            touch $BASH_ENV
            while [ -z "$SIMULATOR_UDID" ]; do
                sleep 1
                source $BASH_ENV
            done
      - run:
          name: Test
          command: |
            xcodebuild test-without-building $XCODEBUILD_ARGS -destination "platform=iOS Simulator,id=$SIMULATOR_UDID" | tee ~/logs/test.log | xcpretty -r junit
      - store_test_results:
          path: build/reports
      - store_artifacts:
          path: ~/logs
  validate-podspec:
    description: |
      Run 'pod lib lint' on a provided .podspec file.
    parameters:
      <<: *executor_parameter
      podspec-path:
        description: Path to the podspec file to validate.
        type: string
      bundle-install:
        description: Should 'bundle install' be run? If true, 'bundle exec' will be used 'pod lib lint'.
        type: boolean
        default: true
      update-specs-repo:
        description: Should the CocoaPods Specs repo be update with 'pod repo update' before validating?
        type: boolean
        default: false
    executor:
      name: default
      xcode-version: << parameters.xcode-version >>
    steps:
      - checkout
      - when:
          condition: << parameters.bundle-install >>
          steps:
            -  install-dependencies:
                 pod-install: false
                 bundle-install: true
      - run:
          name: Fetch CocoaPods Specs
          command: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - when:
          condition: << parameters.update-specs-repo >>
          steps:
            - run:
                name: Update CocoaPods Specs
                command: <<# parameters.bundle-install >>bundle exec<</ parameters.bundle-install >> pod repo update
      - run:
          name: Validate podspec
          command: <<# parameters.bundle-install >>bundle exec<</ parameters.bundle-install >> pod lib lint "<< parameters.podspec-path >>"

commands:
  install-dependencies:
    description: |
      Installs dependencies in the current workspace and caches the results.
    parameters:
      <<: *dependency_parameters
    steps:
      - restore_cache:
          keys:
            - "<< parameters.cache-prefix >>-\
               <<# parameters.bundle-install >>{{ checksum \"<< parameters.bundler-working-directory >>/Gemfile.lock\" }}-<</ parameters.bundle-install >>\
               <<# parameters.pod-install >>{{ checksum \"<< parameters.cocoapods-working-directory >>/Podfile.lock\" }}-<</ parameters.pod-install >>\
               <<# parameters.carthage-update >>{{ checksum \"<< parameters.carthage-working-directory >>/Cartfile.resolved\" }}-<</ parameters.carthage-update >>"
      - when:
          condition: << parameters.bundle-install >>
          steps:
            - run:
                name: Bundle install
                command: cd "<< parameters.bundler-working-directory >>" && bundle install --path=vendor/bundle
      - when:
          condition: << parameters.pod-install >>
          steps:
            - run:
                name: CocoaPods check
                command: |
                  cd "<< parameters.cocoapods-working-directory >>"

                  function lockfile_error () {
                    echo "Podfile and Podfile.lock do not match. Please run 'pod install' and try again."
                  }
                  trap lockfile_error ERR

                  # This verifies that the PODFILE CHECKSUM in Podfile.lock matches Podfile
                  PODFILE_SHA1=$(ruby -e "require 'yaml';puts YAML.load_file('Podfile.lock')['PODFILE CHECKSUM']")
                  echo "$PODFILE_SHA1 *Podfile" | shasum -c

                  # Remove trap (so we don't print the lockfile error)
                  trap - ERR

                  if diff Podfile.lock Pods/Manifest.lock; then
                    echo "Podfile.lock matches Pods/Manifest.lock. Skipping installing pods ..."
                    echo 'export SKIP_POD_INSTALL=1' >> $BASH_ENV
                  else
                    echo "Podfile.lock does not match Pods/Manifest.lock. Pods will be installed ..."
                  fi
            - run:
                name: Fetch CocoaPods Specs (if needed)
                command: test $SKIP_POD_INSTALL || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            - run:
                name: Pod Install (if needed)
                command: |
                  cd "<< parameters.cocoapods-working-directory >>"

                  if [ -n "$SKIP_POD_INSTALL" ]; then
                    echo "Skipping pod install ..."
                  else
                    # Get the shasum of Podfile.lock before installing pods
                    LOCKFILE_SHASUM=$(shasum Podfile.lock)

                    # Install pods
                    <<# parameters.bundle-install >>bundle exec<</ parameters.bundle-install >> pod install

                    # Check that Podfile.lock was unchanged by pod install
                    function lockfile_error () {
                      echo "Podfile.lock was changed by 'pod install'. Please run 'pod install' and try again."
                    }
                    trap lockfile_error ERR

                    echo
                    echo "Checking that Podfile.lock was not modified by 'pod install'"
                    echo "${LOCKFILE_SHASUM}" | shasum -c > /dev/null
                  fi
                environment:
                  COCOAPODS_DISABLE_STATS: true
      - when:
          condition: << parameters.carthage-update >>
          steps:
            - run:
                name: Carthage Update
                command: cd "<< parameters.carthage-working-directory >>" && carthage update --cache-builds

      - save_cache:
          key: "<< parameters.cache-prefix >>-\
                <<# parameters.bundle-install >>{{ checksum \"<< parameters.bundler-working-directory >>/Gemfile.lock\" }}-<</ parameters.bundle-install >>\
                <<# parameters.pod-install >>{{ checksum \"<< parameters.cocoapods-working-directory >>/Podfile.lock\" }}-<</ parameters.pod-install >>\
                <<# parameters.carthage-update >>{{ checksum \"<< parameters.carthage-working-directory >>/Cartfile.resolved\" }}-<</ parameters.carthage-update >>"
          paths:
            - << parameters.bundler-working-directory >>/vendor/bundle
            - << parameters.cocoapods-working-directory >>/Pods/
            - << parameters.carthage-working-directory >>/Carthage/
